#
WEBFiles.bin:
	../PVFS2.exe -h "*.htm, *.html, *.cgi, *.xml, *.bin, *.txt, *wav" -z "*.inc, *.ini, snmp.bib" ../WEBFiles ../webbin WEBFiles.bin

PDIR := ../$(PDIR)
sinclude $(PDIR)Makefile

.PHONY: FORCE
FORCE:
