<h3 class="top">ESP8266EX TCP2UART</h3>
<div class="menu">
	<a href="/index.htm">Main</a>
	<a href="/protect/uart.htm">TCP-UART Settings</a>
	<a href="/protect/wifi_ap.htm">WiFi AP Settings</a>
	<a href="/protect/wifi_sta.htm">WiFi Station Settings</a>
	<a href="/protect/upload.htm">WebFS Upload</a>
	<a href="/protect/setup.htm">Sytem Setup</a>
	<a href="/protect/gpio.htm">GPIO</a>
</div>
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>