<!DOCTYPE html>
<html><head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>ESP8266</title>
	<link rel="stylesheet" href="style.css">
	<script src="/scripts.js"></script>
</head><body onload="reloadTimer.reload(10)">
	<h3 class="top">ESP8266 Built-in Web server <sup>&copy;</sup></h3>
	<div class="content">
		<h3>Timeout <span id='timer'>?</span> sec...</h3>
		Redirect: <a href='/index.htm'>Main</a>

